# Generated by Django 5.2.15 on 2026-07-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=60)),
                ('instructor', models.CharField(max_length=120)),
                ('instructor_avatar', models.URLField(max_length=500)),
                ('playlist_id', models.CharField(max_length=80)),
                ('thumbnail_video_id', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=40, null=True)),
                ('badge_class', models.CharField(blank=True, max_length=40, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=120)),
                ('from_lesson', models.PositiveSmallIntegerField()),
                ('to_lesson', models.PositiveSmallIntegerField()),
                ('goal', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_phases', to='courses.course')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['lesson_number'],
                'unique_together': {('course', 'lesson_number')},
            },
        ),
    ]
