# Generated by Django 5.2.15 on 2026-07-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_cents',
            field=models.PositiveIntegerField(default=4900, help_text='Premium price in USD cents'),
        ),
    ]
